<?php

namespace RLI\Booking\Actions;

use RLI\Booking\Models\{Buyer, Inventory, Product, Voucher};

class AutoOnboardBuyerAction extends ProcessBuyerAction
{
    protected Voucher $voucher;

    public function rules(): array
    {
        $rules = parent::rules();
        $rules['body.inputs.code' ] = ['nullable', 'string'];

        return $rules;
    }

    protected function afterCreatingBuyerProcessing(Buyer $buyer, array $validated): Voucher
    {
        $inventory = $this->getNextInventory($this->project_code);
        $this->voucher = GenerateVoucherAction::run([
            'sku' => $inventory
                ? $inventory->product->sku
                : $this->getDefaultProduct($this->project_code)->sku,
            'email' => $this->getSeller($validated)->email,
        ]);
        $attribs = [
            'property_code' => $inventory
                ? $inventory->property_code
                : $this->project_code,
            'dp_percent' => 0,
            'dp_months' => 24,
        ];
        UpdateOrderAction::run($this->voucher, $attribs);

        return parent::afterCreatingBuyerProcessing($buyer, $validated); // TODO: Change the autogenerated stub
    }

    protected function getVoucher(array $attributes): Voucher
    {
        return $this->voucher;
    }

    protected function getNextInventory(string $project_code): ?Inventory
    {
        return Inventory::first(); //TODO: refactor to a separate Action or Class
    }

    protected function getDefaultProduct(string $project_code): Product
    {
        return Product::first(); //TODO: refactor to a separate Action or Class
    }
}
